# -*- coding: utf-8 -*-

"""
    telstrasmsmessagingapi.models.send_mms_request

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import telstrasmsmessagingapi.models.mms_content

class SendMMSRequest(object):

    """Implementation of the 'Send MMS Request' model.

    TODO: type model description here.

    Attributes:
        mfrom (string): This will be the source address that will be displayed
            on the receiving device. If it is not present then it will default
            to the MSISDN assigned to the app. If replyRequest is set to true,
            then this field will be ignored.
        to (string): This is the destination address.
        subject (string): The subject that will be used in an MMS message.
        reply_request (bool): If set to true, the reply message functionality
            will be implemented and the to address will be ignored if
            present.
        mms_content (list of MMSContent): An Array of content that will be
            sent in an MMS message. If this array is present it will cause the
            “body” element to be ignored, and the message will be sent as an
            MMS.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mfrom" : "from",
        "to" : "to",
        "subject" : "subject",
        "reply_request" : "replyRequest",
        "mms_content" : "MMSContent"
    }

    def __init__(self,
                 mfrom=None,
                 to=None,
                 subject=None,
                 reply_request=None,
                 mms_content=None):
        """Constructor for the SendMMSRequest class"""

        # Initialize members of the class
        self.mfrom = mfrom
        self.to = to
        self.subject = subject
        self.reply_request = reply_request
        self.mms_content = mms_content


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        mfrom = dictionary.get("from")
        to = dictionary.get("to")
        subject = dictionary.get("subject")
        reply_request = dictionary.get("replyRequest")
        mms_content = None
        if dictionary.get("MMSContent") != None:
            mms_content = list()
            for structure in dictionary.get("MMSContent"):
                mms_content.append(telstrasmsmessagingapi.models.mms_content.MMSContent.from_dictionary(structure))

        # Return an object of this model
        return cls(mfrom,
                   to,
                   subject,
                   reply_request,
                   mms_content)


