# -*- coding: utf-8 -*-

"""
    telstrasmsmessagingapi.models.status_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class StatusEnum(object):

    """Implementation of the 'Status' enum.

    TODO: type enum description here.

    Attributes:
        PEND: TODO: type description here.
        SENT: TODO: type description here.
        DELIVRD: TODO: type description here.
        EXPIRED: TODO: type description here.
        DELETED: TODO: type description here.
        UNDVBL: TODO: type description here.
        REJECTED: TODO: type description here.
        READ: TODO: type description here.

    """

    PEND = 'PEND'

    SENT = 'SENT'

    DELIVRD = 'DELIVRD'

    EXPIRED = 'EXPIRED'

    DELETED = 'DELETED'

    UNDVBL = 'UNDVBL'

    REJECTED = 'REJECTED'

    READ = 'READ'

