# -*- coding: utf-8 -*-

"""
    telstrasmsmessagingapi.models.message_type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class MessageTypeEnum(object):

    """Implementation of the 'MessageType' enum.

    TODO: type enum description here.

    Attributes:
        SMS: TODO: type description here.
        MMS: TODO: type description here.
        RCS: TODO: type description here.

    """

    SMS = 'SMS'

    MMS = 'MMS'

    RCS = 'RCS'

