/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.tapi.exceptions;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.telstra.tapi.http.client.HttpContext;

public class ErrorErrorException 
        extends APIException
        implements java.io.Serializable {
    private static final long serialVersionUID = 5098257998516091405L;
    private Integer status;
    private String message;
    /** GETTER
     * The status code.
     */
    @JsonGetter("status")
    public Integer getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * The status code.
     */
    @JsonSetter("status")
    private void setStatus (Integer value) { 
        this.status = value;
    }
 
    /** GETTER
     * Message describing the error.
     */
    @JsonGetter("message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * Message describing the error.
     */
    @JsonSetter("message")
    private void setMessage (String value) { 
        this.message = value;
    }
 
    /**
     * Initialization constructor
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public ErrorErrorException(String reason, HttpContext context) {
        super(reason, context);
    }
}
 