/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.tapi.models;

import java.util.*;

public class InboundPollResponseBuilder {
    //the instance to build
    private InboundPollResponse inboundPollResponse;

    /**
     * Default constructor to initialize the instance
     */
    public InboundPollResponseBuilder() {
        inboundPollResponse = new InboundPollResponse();
    }

    /**
     * The phone number (recipient) that the message was sent to(in
     * E.164 format).
     */
    public InboundPollResponseBuilder to(String to) {
        inboundPollResponse.setTo(to);
        return this;
    }

    /**
     * The phone number (sender) that the message was sent from (in
     * E.164 format).
     */
    public InboundPollResponseBuilder from(String from) {
        inboundPollResponse.setFrom(from);
        return this;
    }

    /**
     * Text body of the message that was sent
     */
    public InboundPollResponseBuilder body(String body) {
        inboundPollResponse.setBody(body);
        return this;
    }

    /**
     * The date and time when the message was recieved by recipient.
     */
    public InboundPollResponseBuilder receivedTimestamp(String receivedTimestamp) {
        inboundPollResponse.setReceivedTimestamp(receivedTimestamp);
        return this;
    }

    /**
     * Indicates if there are more messages that can be polled from
     * the server. 0=No more messages available. Anything else indicates there
     * are more messages on the server.
     */
    public InboundPollResponseBuilder moreMessages(Integer moreMessages) {
        inboundPollResponse.setMoreMessages(moreMessages);
        return this;
    }

    /**
     * Optional message ID of the SMS you sent. Use this ID to view
     * the message status or get responses.
     */
    public InboundPollResponseBuilder messageId(String messageId) {
        inboundPollResponse.setMessageId(messageId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InboundPollResponse build() {
        return inboundPollResponse;
    }
}