/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.tapi.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MMSContent 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5136592586027211997L;
    private String type;
    private String filename;
    private String payload;
    /** GETTER
     * The following types are supported audio/amr 	audio/aac 	audio/mp3
     * 	audio/mpeg3 	audio/mpeg 	audio/mpg 	audio/wav 	audio/3gpp 	audio/mp4
     * 	image/gif 	image/jpeg 	image/jpg 	image/png 	image/bmp 	video/mpeg4
     * 	video/mp4 	video/mpeg 	video/3gpp 	video/3gp 	video/h263 	text/plain
     * 	text/x-vCard 	text/x-vCalendar
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * The following types are supported audio/amr 	audio/aac 	audio/mp3
     * 	audio/mpeg3 	audio/mpeg 	audio/mpg 	audio/wav 	audio/3gpp 	audio/mp4
     * 	image/gif 	image/jpeg 	image/jpg 	image/png 	image/bmp 	video/mpeg4
     * 	video/mp4 	video/mpeg 	video/3gpp 	video/3gp 	video/h263 	text/plain
     * 	text/x-vCard 	text/x-vCalendar
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * The file name to be associated with the content. Some devices
     * will display this file name with a placeholder for the content.
     */
    @JsonGetter("filename")
    public String getFilename ( ) { 
        return this.filename;
    }
    
    /** SETTER
     * The file name to be associated with the content. Some devices
     * will display this file name with a placeholder for the content.
     */
    @JsonSetter("filename")
    public void setFilename (String value) { 
        this.filename = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("payload")
    public String getPayload ( ) { 
        return this.payload;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("payload")
    public void setPayload (String value) { 
        this.payload = value;
    }
 
}
 