/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.tapi.models;

import java.util.*;

public class MMSContentBuilder {
    //the instance to build
    private MMSContent mMSContent;

    /**
     * Default constructor to initialize the instance
     */
    public MMSContentBuilder() {
        mMSContent = new MMSContent();
    }

    /**
     * The following types are supported audio/amr 	audio/aac 	audio/mp3
     * 	audio/mpeg3 	audio/mpeg 	audio/mpg 	audio/wav 	audio/3gpp 	audio/mp4
     * 	image/gif 	image/jpeg 	image/jpg 	image/png 	image/bmp 	video/mpeg4
     * 	video/mp4 	video/mpeg 	video/3gpp 	video/3gp 	video/h263 	text/plain
     * 	text/x-vCard 	text/x-vCalendar
     */
    public MMSContentBuilder type(String type) {
        mMSContent.setType(type);
        return this;
    }

    /**
     * The file name to be associated with the content. Some devices
     * will display this file name with a placeholder for the content.
     */
    public MMSContentBuilder filename(String filename) {
        mMSContent.setFilename(filename);
        return this;
    }

    public MMSContentBuilder payload(String payload) {
        mMSContent.setPayload(payload);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MMSContent build() {
        return mMSContent;
    }
}