/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.tapi.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SendMMSRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5540698322169811011L;
    private String from;
    private String to;
    private String subject;
    private boolean replyRequest;
    private List<MMSContent> mMSContent;
    /** GETTER
     * This will be the source address that will be displayed on the
     * receiving device. If it is not present then it will default to the MSISDN
     * assigned to the app. If replyRequest is set to true, then this field will
     * be ignored.
     */
    @JsonGetter("from")
    public String getFrom ( ) { 
        return this.from;
    }
    
    /** SETTER
     * This will be the source address that will be displayed on the
     * receiving device. If it is not present then it will default to the MSISDN
     * assigned to the app. If replyRequest is set to true, then this field will
     * be ignored.
     */
    @JsonSetter("from")
    public void setFrom (String value) { 
        this.from = value;
    }
 
    /** GETTER
     * This is the destination address.
     */
    @JsonGetter("to")
    public String getTo ( ) { 
        return this.to;
    }
    
    /** SETTER
     * This is the destination address.
     */
    @JsonSetter("to")
    public void setTo (String value) { 
        this.to = value;
    }
 
    /** GETTER
     * The subject that will be used in an MMS message.
     */
    @JsonGetter("subject")
    public String getSubject ( ) { 
        return this.subject;
    }
    
    /** SETTER
     * The subject that will be used in an MMS message.
     */
    @JsonSetter("subject")
    public void setSubject (String value) { 
        this.subject = value;
    }
 
    /** GETTER
     * If set to true, the reply message functionality will be implemented
     * and the to address will be ignored if present.
     */
    @JsonGetter("replyRequest")
    public boolean getReplyRequest ( ) { 
        return this.replyRequest;
    }
    
    /** SETTER
     * If set to true, the reply message functionality will be implemented
     * and the to address will be ignored if present.
     */
    @JsonSetter("replyRequest")
    public void setReplyRequest (boolean value) { 
        this.replyRequest = value;
    }
 
    /** GETTER
     * An Array of content that will be sent in an MMS message. If this
     * array is present it will cause the “body” element to be ignored, and the
     * message will be sent as an MMS.
     */
    @JsonGetter("MMSContent")
    public List<MMSContent> getMMSContent ( ) { 
        return this.mMSContent;
    }
    
    /** SETTER
     * An Array of content that will be sent in an MMS message. If this
     * array is present it will cause the “body” element to be ignored, and the
     * message will be sent as an MMS.
     */
    @JsonSetter("MMSContent")
    public void setMMSContent (List<MMSContent> value) { 
        this.mMSContent = value;
    }
 
}
 