/**
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Servers = {

    /**
     * TODO: Write general description for this element
     */
    MDEFAULT: 'default',

    /**
     * TODO: Write general description for this element
     */
    AUTHORIZATION: 'authorization',

};

module.exports = Servers;
