/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package net.telstra.tdev.apipractice.slot2.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MessageSentResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4781982533399704452L;
    private List<Message> messages;
    private String messageType;
    private int numberSegments;
    private int numberDestinations;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("messages")
    public List<Message> getMessages ( ) { 
        return this.messages;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("messages")
    public void setMessages (List<Message> value) { 
        this.messages = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("MessageType")
    public String getMessageType ( ) { 
        return this.messageType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("MessageType")
    public void setMessageType (String value) { 
        this.messageType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("NumberSegments")
    public int getNumberSegments ( ) { 
        return this.numberSegments;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("NumberSegments")
    public void setNumberSegments (int value) { 
        this.numberSegments = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("NumberDestinations")
    public int getNumberDestinations ( ) { 
        return this.numberDestinations;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("NumberDestinations")
    public void setNumberDestinations (int value) { 
        this.numberDestinations = value;
    }
 
}
 