/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package net.telstra.tdev.apipractice.slot2.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum OAuthScopeEnum {
    SMS; //TODO: Write general description for this element

    private static TreeMap<String, OAuthScopeEnum> valueMap = new TreeMap<String, OAuthScopeEnum>();
    private String value;

    static {
        SMS.value = "NSMS";

        valueMap.put("NSMS", SMS);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static OAuthScopeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of OAuthScopeEnum values to list of string values
     * @param toConvert The list of OAuthScopeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<OAuthScopeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (OAuthScopeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 