/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package net.telstra.tdev.apipractice.slot2.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class OutboundPollResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5239922172942496126L;
    private String to;
    private String receivedTimestamp;
    private String sentTimestamp;
    private StatusEnum status;
    /** GETTER
     * The phone number (recipient) the message was sent to (in E.164 format).
     */
    @JsonGetter("to")
    public String getTo ( ) { 
        return this.to;
    }
    
    /** SETTER
     * The phone number (recipient) the message was sent to (in E.164 format).
     */
    @JsonSetter("to")
    public void setTo (String value) { 
        this.to = value;
    }
 
    /** GETTER
     * The date and time when the message was recieved by recipient.
     */
    @JsonGetter("receivedTimestamp")
    public String getReceivedTimestamp ( ) { 
        return this.receivedTimestamp;
    }
    
    /** SETTER
     * The date and time when the message was recieved by recipient.
     */
    @JsonSetter("receivedTimestamp")
    public void setReceivedTimestamp (String value) { 
        this.receivedTimestamp = value;
    }
 
    /** GETTER
     * The date and time when the message was sent.
     */
    @JsonGetter("sentTimestamp")
    public String getSentTimestamp ( ) { 
        return this.sentTimestamp;
    }
    
    /** SETTER
     * The date and time when the message was sent.
     */
    @JsonSetter("sentTimestamp")
    public void setSentTimestamp (String value) { 
        this.sentTimestamp = value;
    }
 
    /** GETTER
     * Delivery status of the message
     */
    @JsonGetter("status")
    public StatusEnum getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * Delivery status of the message
     */
    @JsonSetter("status")
    public void setStatus (StatusEnum value) { 
        this.status = value;
    }
 
}
 