/**
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of InboundPollResponse
 */
class InboundPollResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.to = this.constructor.getValue(obj.to);
        this.from = this.constructor.getValue(obj.from);
        this.body = this.constructor.getValue(obj.body);
        this.receivedTimestamp = this.constructor.getValue(obj.receivedTimestamp);
        this.moreMessages = this.constructor.getValue(obj.moreMessages);
        this.messageId = this.constructor.getValue(obj.messageId);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'to', realName: 'to' },
            { name: 'from', realName: 'from' },
            { name: 'body', realName: 'body' },
            { name: 'receivedTimestamp', realName: 'receivedTimestamp' },
            { name: 'moreMessages', realName: 'moreMessages' },
            { name: 'messageId', realName: 'messageId' },
        ]);
    }
}

module.exports = InboundPollResponse;
