/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package net.telstra.tdev.apipractice.slot2;

import net.telstra.tdev.apipractice.slot2.models.OAuthToken;

public interface OAuthTokenUpdateCallBack {

    void tokenUpdate(OAuthToken oAuthToken);

}
