/**
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Servers = {

    /**
     * TODO: Write general description for this element
     */
    MDEFAULT: 'default',

    /**
     * TODO: Write general description for this element
     */
    ACCESS_TOKEN_SERVER: 'access token server',

};

module.exports = Servers;
