/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.tapi;

import com.telstra.tapi.models.OAuthToken;

public interface OAuthTokenUpdateCallBack {

    void tokenUpdate(OAuthToken oAuthToken);

}
