/*
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.tapi;

import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import com.telstra.tapi.models.OAuthScopeEnum;
import com.telstra.tapi.controllers.OAuthAuthorizationController;
import com.telstra.tapi.models.OAuthToken;
import com.telstra.tapi.exceptions.APIException;
import com.telstra.tapi.http.client.APICallBack;
import com.telstra.tapi.http.client.HttpContext;
import com.telstra.tapi.controllers.syncwrapper.APICallBackCatcher;
import com.mashape.unirest.http.utils.Base64Coder;

/**
 * Utility class for OAuth 2 authorization and token management
 */
public class OAuthManager {
    /**
     * The reference to singleton instance of this class
     */
    private static OAuthManager instance;

    /**
     * Singleton instance of OAuth 2 API controller 
     */
    private OAuthAuthorizationController oAuthApi;

    /**
     * Constructor
     */
    private OAuthManager() {
        oAuthApi = OAuthAuthorizationController.getInstance();
    }

    /**
     * Returns the *Singleton* instance of this class.
     * @return Singleton instance
     */
    public static OAuthManager getInstance() {
        if (instance == null) {
            synchronized (OAuthManager.class) {
                if (instance == null) {
                    instance = new OAuthManager();
                }
            }
        }
        return instance;
    }

    /**
     * Asynchronously authorize the client with the OAuth provider
     * @param scope List of scopes needed
     * @param additionalParameters Additional parameters to send during authorization
     * @param callback Callback
     */
    public void authorizeAsync(final List<OAuthScopeEnum> scope, final Map<String, Object> additionalParameters,
            final APICallBack<OAuthToken> callback) {
        
        final Map<String, Object> aparams = additionalParameters == null ? new HashMap<String, Object>()
                : additionalParameters;
        
        oAuthApi.createRequestTokenAsync(
            getBasicAuthForClient(),
            stringJoin(scope, " "),
            aparams,
            new APICallBack<OAuthToken>() {

                    public void onSuccess(HttpContext context, OAuthToken response) {
                        updateOAuthToken(response);
                        callback.onSuccess(context, response);
                    }

                    public void onFailure(HttpContext context, Throwable error) {
                        callback.onFailure(context, error);
                    }
                });
    }
    
    /**
     * Asynchronously authorize the client with the OAuth provider
     * @param callback Callback
     */
    public void authorizeAsync(final APICallBack<OAuthToken> callback) {
        authorizeAsync(null, null, callback);
    }

    /**
     * Authorize the client with the OAuth provider
     * @param scope List of scopes needed
     * @param additionalParameters Additional parameters to send during authorization
     */
    public OAuthToken authorize(List<OAuthScopeEnum> scope, Map<String, Object> additionalParameters)
            throws Throwable {
        
        APICallBackCatcher<OAuthToken> callback = new APICallBackCatcher<OAuthToken>();
        authorizeAsync(scope, additionalParameters, callback);
        if (!callback.isSuccess())
            throw callback.getError();
        return callback.getResult();
    }
    
    /**
     * Authorize the client with the OAuth provider
     */
    public OAuthToken authorize() throws Throwable {
        return authorize(null, null);
    }

    /**
     * Has the OAuth token expired?
     * @return True if expired
     */
    public boolean isTokenExpired() {
        return Configuration.oAuthToken != null
                && Configuration.oAuthToken.getExpiry() < (System.currentTimeMillis() / 1000L);
    }

    /**
     * Check if client is authorized, else attempt to get token
     * @throws Throwable APIException or other exception in case of error
     */
    public void checkAuthorization() throws Throwable {
        if (Configuration.oAuthToken == null) {
            authorize();
            return;
        }
    }

    /**
     * Create authorization header for API calls
     * @return Authorization header
     */
    public String getAuthorizationHeader() {
        return "Bearer " + Configuration.oAuthToken.getAccessToken();
    }

    /**
     * Update OAuth token in configuration
     * @param oAuthToken OAuth token
     */
    private static void updateOAuthToken(OAuthToken oAuthToken) {
        //calculate token expiry time in unix time (UTC)
        if (oAuthToken.getExpiresIn() != null && oAuthToken.getExpiresIn() != 0) {
            oAuthToken.setExpiry((System.currentTimeMillis() / 1000L) + oAuthToken.getExpiresIn());
        }

        //update token and call callback
        Configuration.oAuthToken = oAuthToken;
        if (Configuration.oAuthTokenUpdateCallBack != null) {
            Configuration.oAuthTokenUpdateCallBack.tokenUpdate(oAuthToken);
        }
    }

    /**
     * Build authorization header value for basic auth
     * @return Authorization header value for this client
     */
    private static String getBasicAuthForClient() {
        return "Basic " + Base64Coder.encodeString(Configuration.oAuthClientId + ":" + Configuration.oAuthClientSecret);
    }

    /**
     * Join string collection elements using delimiter
     * @param col String collection to join
     * @param delim Delimiter
     * @return String joined by delimiter
     */
    private static String stringJoin(Collection<?> col, String delim) {
        if (col == null)
            return null;
        StringBuilder sb = new StringBuilder();
        Iterator<?> iter = col.iterator();
        if (iter.hasNext())
            sb.append(iter.next().toString());
        while (iter.hasNext()) {
            sb.append(delim);
            sb.append(iter.next().toString());
        }
        return sb.toString();
    }
}
