/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.tapi;

import com.telstra.tapi.controllers.*;
import com.telstra.tapi.http.client.HttpClient;

public class TelstraSMSMessagingAPIClient {
    /**
     * Singleton access to Messaging controller
     * @return	Returns the MessagingController instance 
     */
    public MessagingController getMessaging() {
        return MessagingController.getInstance();
    }

    /**
     * Singleton access to OAuthAuthorization controller
     * @return	Returns the OAuthAuthorizationController instance 
     */
    public OAuthAuthorizationController getOAuthAuthorization() {
        return OAuthAuthorizationController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Get authentication manager
     */
    public OAuthManager auth() {
        return OAuthManager.getInstance();
    }

    /**
     * Default constructor 
     */     
    public TelstraSMSMessagingAPIClient() {
    }

    /**
     * Client initialization constructor 
     */     
    public TelstraSMSMessagingAPIClient(String oAuthClientId, String oAuthClientSecret) {
        this();
        Configuration.oAuthClientId = oAuthClientId;
        Configuration.oAuthClientSecret = oAuthClientSecret;
    }
}