/**
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const MessageTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    SMS: 'SMS',

    /**
     * TODO: Write general description for this element
     */
    MMS: 'MMS',

    /**
     * TODO: Write general description for this element
     */
    RCS: 'RCS',

};

module.exports = MessageTypeEnum;
