/**
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const OAuthScopeEnum = {

    /**
     * NSMS
     */
    NSMS: 'NSMS',

};

module.exports = OAuthScopeEnum;
