/**
 * TelstraMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const StatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    PEND: 'PEND',

    /**
     * TODO: Write general description for this element
     */
    SENT: 'SENT',

    /**
     * TODO: Write general description for this element
     */
    DELIVRD: 'DELIVRD',

    /**
     * TODO: Write general description for this element
     */
    EXPIRED: 'EXPIRED',

    /**
     * TODO: Write general description for this element
     */
    DELETED: 'DELETED',

    /**
     * TODO: Write general description for this element
     */
    UNDVBL: 'UNDVBL',

    /**
     * TODO: Write general description for this element
     */
    REJECTED: 'REJECTED',

    /**
     * TODO: Write general description for this element
     */
    READ: 'READ',

};

module.exports = StatusEnum;
