# -*- coding: utf-8 -*-

"""
    telstrasmsmessagingapi.telstra_sms_messaging_api_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .configuration import Configuration
from .controllers.sms_controller import SMSController

class TelstrasmsmessagingapiClient(object):

    config = Configuration

    @lazy_property
    def sms(self):
        return SMSController()


    def __init__(self, 
                 o_auth_access_token = None):
        if o_auth_access_token != None:
            Configuration.o_auth_access_token = o_auth_access_token


