# -*- coding: utf-8 -*-

"""
    telstramessagingapi.models.message

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""


class Message(object):

    """Implementation of the 'Message' model.

    TODO: type model description here.

    Attributes:
        to (string): TODO: type description here.
        delivery_status (string): TODO: type description here.
        message_id (string): TODO: type description here.
        message_status_link (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "to" : "to",
        "delivery_status" : "deliveryStatus",
        "message_id" : "messageId",
        "message_status_link" : "messageStatusLink"
    }

    def __init__(self,
                 to=None,
                 delivery_status=None,
                 message_id=None,
                 message_status_link=None):
        """Constructor for the Message class"""

        # Initialize members of the class
        self.to = to
        self.delivery_status = delivery_status
        self.message_id = message_id
        self.message_status_link = message_status_link


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        to = dictionary.get("to")
        delivery_status = dictionary.get("deliveryStatus")
        message_id = dictionary.get("messageId")
        message_status_link = dictionary.get("messageStatusLink")

        # Return an object of this model
        return cls(to,
                   delivery_status,
                   message_id,
                   message_status_link)


