# -*- coding: utf-8 -*-

"""
    telstramessagingapi.models.o_auth_scope_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class OAuthScopeEnum(object):

    """Implementation of the 'OAuth Scope' enum.

    OAuth 2 scopes supported by the API

    Attributes:
        NSMS: NSMS

    """

    NSMS = 'NSMS'

