# -*- coding: utf-8 -*-

"""
    telstrasmsmessagingapi.telstra_sms_messaging_api_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .configuration import Configuration
from .http.auth.o_auth_2 import OAuth2
from .controllers.messaging_controller import MessagingController
from .controllers.o_auth_authorization_controller import OAuthAuthorizationController

class TelstrasmsmessagingapiClient(object):

    auth = OAuth2
    config = Configuration

    @lazy_property
    def messaging(self):
        return MessagingController()

    @lazy_property
    def o_auth_authorization(self):
        return OAuthAuthorizationController()


    def __init__(self, 
                 o_auth_client_id = None,
                 o_auth_client_secret = None):
        if o_auth_client_id != None:
            Configuration.o_auth_client_id = o_auth_client_id
        if o_auth_client_secret != None:
            Configuration.o_auth_client_secret = o_auth_client_secret


