# -*- coding: utf-8 -*-

"""
   telstramessagingapi.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
from .api_helper import APIHelper

class Configuration(object):

    """A class used for configuring the SDK by a user.

    This class need not be instantiated and all properties and methods
    are accessible without instance creation.

    """

    # Set the array parameter serialization method
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    array_serialization = "indexed"

    # An enum for SDK environments
    class Environment(object):
        PRODUCTION = 0

    # An enum for API servers
    class Server(object):
        DEFAULT = 0
        ACCESS_TOKEN_SERVER = 1

    # The environment in which the SDK is running
    environment = Environment.PRODUCTION

    # OAuth 2 Client ID
    # TODO: Set an appropriate value
    o_auth_client_id = "TODO: Replace"

    # OAuth 2 Client Secret
    # TODO: Set an appropriate value
    o_auth_client_secret = "TODO: Replace"

    # Object for storing information about the OAuth token
    o_auth_token = None

    # Callback to be called when OAuth token is acquired or refreshed
    o_auth_callback = None

    # All the environments the SDK can run in
    environments = {
        Environment.PRODUCTION: {
            Server.DEFAULT: 'https://tapi.telstra.com/v2',
            Server.ACCESS_TOKEN_SERVER: 'https://sapi.telstra.com/v1/oauth',
        },
    }

    @classmethod
    def get_base_uri(cls, server=Server.DEFAULT):
        """Generates the appropriate base URI for the environment and the server.

        Args:
            server (Configuration.Server): The server enum for which the base URI is required.

        Returns:
            String: The base URI.

        """
        parameters = {
        }
        return APIHelper.append_url_with_template_parameters(cls.environments[cls.environment][server], parameters)
